#!/usr/bin/env node
var ic = require('./wixtoolset.js');
var args = process.argv.slice(2);
var options = {};

for (var i=0; i<args.length; i++) {
	if (/^\-/.test(args[i])) {
		var s = args[i].replace(/^\-+/, "").split("=");
		options[s[0]] = s.length > 1 ? s.slice(1).join("=") : true;
	} 
}

ic.call(ic, options);
